name: "Unit testing"
on: 
  push:
    branches:
      - main
    paths:
      - "lib/**"
  pull_request:
    branches:
      - main
    paths:
      - "lib/**"
jobs:
  client-side-unit-testing:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.2'
      - run: flutter pub get
      - run: flutter test
